### ISSUE TITLE
Sourcemaps not working with --manifest

### ISSUE THREAD

**Issue by amstiel** [stepanzin/gulpmeister#11]
## Description 
Sourcemaps not working with manifest. Chrome devtools don't show exact source file of the styles, it show whole bundle as source instead.

## Steps to Reproduce
   1.  Build assets using `--manifest` flag (e.g `yarn build:dev`)
   2. Run server, open devtools

## Actual result:
![image](https://user-images.githubusercontent.com/9428948/73908445-74ae7880-48f5-11ea-89dc-83177418d082.png)

## Expected result:
![image](https://user-images.githubusercontent.com/9428948/73908475-86901b80-48f5-11ea-92cb-8b7a1d92da42.png)

**Comment by Grawl** [comment]
it should not work with manifest because it contains mappings from built assets to minified ones

**Comment by amstiel** [comment]
So, I can't build "cachebusted" assets with sourcemaps? I don't think so 😎 . I'll fix this issue later.

**Comment by Grawl** [comment]
you dont want to have sourcemaps in production/minified build

**Comment by amstiel** [comment]
Flag `--manifest` is for cache busting, not for minifying (we have `--prod` for that). I want cache busting on staging server, and I want sourcemaps also.

**Comment by Grawl** [comment]
ok I got it
