### ISSUE TITLE
BrowserSync reloads page on styles change

### ISSUE THREAD

**Issue by amstiel** [stepanzin/gulpmeister#12]
## Description 
BrowserSync can inject styles without reloading page. See [this](https://www.browsersync.io/docs/gulp#gulp-sass-css) for details. But now it's reloading page after any styles change.

## Steps to Reproduce
   1. Run build with `--serve` flag
   2. Change any scss rule

## Actual result:
BrowserSync reloads page

## Expected result:
BrowserSync injects css "on the fly"

**Comment by Grawl** [comment]
lol such a generic bundler issue
